/**
 * Server-side mirror of every shop catalog's prices, so purchases can be
 * validated against the *real* price instead of trusting whatever the
 * client sends. This file has no automatic link to the frontend catalogs
 * (frontend/src/ts/*-items.ts) - if a price changes there, it must be
 * updated here too. Kept intentionally minimal (id/price/category only,
 * not full display metadata) to make that sync easier to keep correct.
 *
 * side-images is NOT here - its prices are admin-configurable at runtime
 * and live in Firestore (schoolConfig/sideImages), not a fixed catalog, so
 * buy-item.ts reads that document directly instead of using this table.
 */

export type CatalogItem = {
  price?: number;
  requiresAchievement?: string;
  /** Avatar only - which equip slot this item occupies. */
  category?: string;
};

export type ShopId =
  | "house"
  | "pet"
  | "avatar"
  | "hands"
  | "rgbPalette"
  | "keyboardSkin"
  | "keypressEffect"
  | "caretEffect"
  | "backdrop"
  | "animalAvatar";

/** users/{uid} field each shop's ownership map is stored under. */
export const OWNED_FIELD: Record<ShopId, string> = {
  house: "ownedHouseItems",
  pet: "ownedPets",
  avatar: "ownedCostumes",
  hands: "ownedHandStyles",
  rgbPalette: "ownedRgbPalettes",
  keyboardSkin: "ownedKeyboardSkins",
  keypressEffect: "ownedKeypressEffects",
  caretEffect: "ownedCaretEffects",
  backdrop: "ownedBackdrops",
  animalAvatar: "ownedAnimalAvatars",
};

/** users/{uid} field for the "currently equipped/selected" id, if the shop has one. */
export const SELECTED_FIELD: Partial<Record<ShopId, string>> = {
  hands: "selectedHandStyle",
  rgbPalette: "selectedRgbPalette",
  keypressEffect: "selectedKeypressEffect",
  caretEffect: "selectedCaretEffect",
  backdrop: "selectedBackdrop",
  animalAvatar: "equippedAnimalAvatar",
};

export const CATALOGS: Record<ShopId, Record<string, CatalogItem>> = {
  house: {
    rug: { price: 20 },
    couch: { price: 40 },
    bed: { price: 45 },
    chair: { price: 25 },
    plant: { price: 20 },
    tree: { price: 35 },
    toybox: { price: 30 },
    bookshelf: { price: 40 },
    window: { price: 30 },
    clock: { price: 25 },
    frame: { price: 25 },
    lights: { price: 30 },
    "blue-rug": { price: 20 },
    cat: { price: 40 },
    guitar: { price: 35 },
    fishtank: { price: 35 },
    "gaming-setup": { price: 90 },
    "trophy-shelf": { price: 110 },
    table: { price: 30 },
    tv: { price: 65 },
    mirror: { price: 30 },
    piano: { price: 100 },
    lamp: { price: 25 },
    cabinet: { price: 45 },
    // Pixel-art furniture sprites (see house-sprite-items.ts)
    "armchair-olive": { price: 60 },
    "armchair-single": { price: 60 },
    "bar-cabinet": { price: 60 },
    bathtub: { price: 60 },
    "single-bed": { price: 60 },
    "bookshelf-drawers": { price: 85 },
    "bookshelf-full": { price: 85 },
    "cabinet-medium": { price: 60 },
    "cabinet-tall-plain": { price: 45 },
    "chair-1": { price: 45 },
    "chair-2": { price: 30 },
    "coat-hooks": { price: 45 },
    "coat-rack": { price: 45 },
    dresser: { price: 60 },
    "floor-lamp": { price: 45 },
    fridge: { price: 60 },
    "ironing-board": { price: 45 },
    nightstand: { price: 45 },
    "pedestal-sink": { price: 45 },
    "potted-flower": { price: 30 },
    "round-table": { price: 45 },
    "rug-oval-dark": { price: 45 },
    "rug-oval-small": { price: 30 },
    "rug-striped": { price: 45 },
    "side-table-small": { price: 45 },
    "small-drawer-table": { price: 45 },
    "sofa-plain": { price: 60 },
    "standing-mirror": { price: 60 },
    "table-lamp": { price: 30 },
    "vanity-mirror": { price: 45 },
    "wardrobe-dark": { price: 45 },
    "wardrobe-double": { price: 60 },
    "wardrobe-mirror": { price: 45 },
    "wood-stove": { price: 60 },
    // Small decorative items (see house-small-items.ts)
    "bottle-blue-small-1": { price: 10 },
    "bottle-blue-small-2": { price: 10 },
    "bottle-blue": { price: 15 },
    "bottle-red-small": { price: 10 },
    "bottle-red": { price: 15 },
    "bottle-tan": { price: 15 },
    "bottle-white": { price: 15 },
    "bottle-yellow": { price: 15 },
    "bowl-food-oval": { price: 15 },
    "bowl-white": { price: 15 },
    "bread-loaf": { price: 15 },
    "bread-pie-round": { price: 15 },
    "bread-small": { price: 10 },
    broom: { price: 15 },
    burger: { price: 15 },
    "coat-hanger": { price: 15 },
    "cup-spoon-brown": { price: 15 },
    "cup-spoon-white": { price: 15 },
    "cup-teal": { price: 15 },
    "dog-bone": { price: 15 },
    "drawer-box-small": { price: 20 },
    "drawer-box": { price: 15 },
    "drawer-small-brown": { price: 20 },
    "drawer-with-items": { price: 20 },
    "dried-fish": { price: 15 },
    "fish-tank": { price: 20 },
    "food-strip-1": { price: 15 },
    "food-strip-2": { price: 15 },
    "food-strip-3": { price: 15 },
    "fruit-dark-red": { price: 15 },
    "mug-brown": { price: 15 },
    "nightstand-small-dark": { price: 10 },
    "open-book": { price: 15 },
    "picture-frame-purple": { price: 20 },
    "picture-frame-red": { price: 20 },
    "plate-food-1": { price: 15 },
    "plate-food-2": { price: 15 },
    "plate-food-3": { price: 15 },
    "plate-white-oval": { price: 15 },
    "pot-brown": { price: 20 },
    "pot-maroon": { price: 20 },
    "pot-red-1": { price: 20 },
    "pot-red-2": { price: 20 },
    "potted-cactus": { price: 15 },
    "potted-plant-small": { price: 20 },
    "rolling-pin": { price: 15 },
    "rubber-duck": { price: 15 },
    "spice-bottle": { price: 10 },
    teapot: { price: 20 },
    "tissue-cloud": { price: 10 },
    "wall-clock": { price: 20 },
    // Room wall/floor finishes (see house-themes.ts). The free "plain"
    // default is deliberately absent - nothing to buy.
    "cozy-wood": { price: 80 },
    "mint-tile": { price: 80 },
    "night-sky": { price: 120 },
    candy: { price: 120 },
    meadow: { price: 120 },
  },
  pet: {
    dog: { price: 60 },
    cat: { price: 60 },
    rabbit: { price: 50 },
    bird: { price: 70 },
    butterfly: { price: 55 },
  },
  avatar: {
    red: { category: "color", price: 20 },
    blue: { category: "color", price: 20 },
    green: { category: "color", price: 20 },
    purple: { category: "color", price: 30 },
    yellow: { category: "color", price: 30 },
    orange: { category: "color", price: 30 },
    pink: { category: "color", price: 30 },
    teal: { category: "color", price: 35 },
    dark: { category: "color", price: 35 },
    "short-hair": { category: "hair", price: 35 },
    "long-hair": { category: "hair", price: 40 },
    ponytail: { category: "hair", price: 40 },
    "spiky-hair": { category: "hair", price: 45 },
    cap: { category: "hat", price: 40 },
    beanie: { category: "hat", price: 40 },
    party: { category: "hat", price: 50 },
    headband: { category: "hat", price: 30 },
    halo: { category: "hat", requiresAchievement: "accuracy-perfect" },
    wizard: { category: "hat", requiresAchievement: "speed-50" },
    crown: { category: "hat", requiresAchievement: "streak-30" },
    pumpkin: { category: "hat", price: 60 },
    santa: { category: "hat", price: 60 },
    glasses: { category: "accessory", price: 30 },
    bow: { category: "accessory", price: 30 },
    mustache: { category: "accessory", price: 40 },
    earrings: { category: "accessory", price: 30 },
    necklace: { category: "accessory", price: 40 },
    heart: { category: "accessory", price: 50 },
    star: { category: "accessory", price: 60 },
    freckles: { category: "accessory", price: 25 },
    headphones: { category: "accessory", price: 45 },
    scarf: { category: "accessory", price: 40 },
    sleepy: { category: "face", price: 25 },
    wink: { category: "face", price: 25 },
    surprised: { category: "face", price: 25 },
    angry: { category: "face", price: 25 },
    laughing: { category: "face", price: 30 },
    starstruck: { category: "face", price: 30 },
    "dots-bg": { category: "background", price: 35 },
    "stars-bg": { category: "background", price: 45 },
    "sunburst-bg": { category: "background", price: 55 },
    "grid-bg": { category: "background", price: 35 },
    "waves-bg": { category: "background", price: 45 },
    "rainbow-bg": { category: "background", price: 55 },
    "hearts-bg": { category: "background", price: 45 },
    "gold-highlight": { category: "highlight", price: 60 },
    "ice-highlight": { category: "highlight", price: 60 },
    "fire-highlight": { category: "highlight", price: 60 },
    "royal-highlight": {
      category: "highlight",
      requiresAchievement: "streak-60",
    },
    "emerald-highlight": { category: "highlight", price: 60 },
    "rose-highlight": { category: "highlight", price: 60 },
    "short-hair-square": { category: "hair", price: 35 },
    "long-hair-square": { category: "hair", price: 40 },
    "ponytail-square": { category: "hair", price: 40 },
    "spiky-hair-square": { category: "hair", price: 45 },
    "cap-square": { category: "hat", price: 40 },
    "beanie-square": { category: "hat", price: 40 },
    "party-square": { category: "hat", price: 50 },
    "headband-square": { category: "hat", price: 30 },
    "short-hair-oval": { category: "hair", price: 35 },
    "spiky-hair-oval": { category: "hair", price: 45 },
    "cap-oval": { category: "hat", price: 40 },
    "headband-oval": { category: "hat", price: 30 },
    "short-hair-hexagon": { category: "hair", price: 35 },
    "spiky-hair-hexagon": { category: "hair", price: 45 },
    "cap-hexagon": { category: "hat", price: 40 },
    "headband-hexagon": { category: "hat", price: 30 },
    "short-hair-cloud": { category: "hair", price: 35 },
    "spiky-hair-cloud": { category: "hair", price: 45 },
    "cap-cloud": { category: "hat", price: 40 },
    "headband-cloud": { category: "hat", price: 30 },
  },
  hands: {
    classic: {},
    robot: { price: 50 },
    kingfish: { price: 50 },
    dark: { price: 40 },
    warmtone: { price: 40 },
    golden: { price: 120 },
  },
  rgbPalette: {
    rainbow: {},
    ocean: { price: 40 },
    sunset: { price: 40 },
    forest: { price: 40 },
    royal: { price: 60 },
  },
  keyboardSkin: {
    wood: { price: 50 },
    glass: { price: 60 },
  },
  keypressEffect: {
    none: {},
    spark: { price: 30 },
    ripple: { price: 30 },
    confetti: { price: 50 },
  },
  caretEffect: {
    none: {},
    glow: { price: 30 },
    comet: { price: 40 },
    sparkle: { price: 40 },
  },
  backdrop: {
    none: {},
    ocean: { price: 30 },
    wood: { price: 30 },
    space: { price: 50 },
  },
  animalAvatar: {
    "round-bear": { price: 200 },
    "round-buffalo": { price: 200 },
    "round-chick": { price: 200 },
    "round-chicken": { price: 200 },
    "round-cow": { price: 200 },
    "round-crocodile": { price: 200 },
    "round-dog": { price: 200 },
    "round-duck": { price: 200 },
    "round-elephant": { price: 200 },
    "round-frog": { price: 200 },
    "round-giraffe": { price: 200 },
    "round-goat": { price: 200 },
    "round-gorilla": { price: 200 },
    "round-hippo": { price: 200 },
    "round-horse": { price: 200 },
    "round-monkey": { price: 200 },
    "round-moose": { price: 200 },
    "round-narwhal": { price: 200 },
    "round-owl": { price: 200 },
    "round-panda": { price: 200 },
    "round-parrot": { price: 200 },
    "round-penguin": { price: 200 },
    "round-pig": { price: 200 },
    "round-rabbit": { price: 200 },
    "round-rhino": { price: 200 },
    "round-sloth": { price: 200 },
    "round-snake": { price: 200 },
    "round-walrus": { price: 200 },
    "round-whale": { price: 200 },
    "round-zebra": { price: 200 },
    "square-bear": { price: 200 },
    "square-buffalo": { price: 200 },
    "square-chick": { price: 200 },
    "square-chicken": { price: 200 },
    "square-cow": { price: 200 },
    "square-crocodile": { price: 200 },
    "square-dog": { price: 200 },
    "square-duck": { price: 200 },
    "square-elephant": { price: 200 },
    "square-frog": { price: 200 },
    "square-giraffe": { price: 200 },
    "square-goat": { price: 200 },
    "square-gorilla": { price: 200 },
    "square-hippo": { price: 200 },
    "square-horse": { price: 200 },
    "square-monkey": { price: 200 },
    "square-moose": { price: 200 },
    "square-narwhal": { price: 200 },
    "square-owl": { price: 200 },
    "square-panda": { price: 200 },
    "square-parrot": { price: 200 },
    "square-penguin": { price: 200 },
    "square-pig": { price: 200 },
    "square-rabbit": { price: 200 },
    "square-rhino": { price: 200 },
    "square-sloth": { price: 200 },
    "square-snake": { price: 200 },
    "square-walrus": { price: 200 },
    "square-whale": { price: 200 },
    "square-zebra": { price: 200 },
  },
};
