import { HouseSpriteItem } from "./house-items";

function buildImageMap(files: Record<string, string>): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [path, url] of Object.entries(files)) {
    const match = /([^/]+\.png)$/.exec(path);
    if (match?.[1] !== undefined) map[match[1]] = url;
  }
  return map;
}

const images = buildImageMap(
  import.meta.glob("../../assets/furnitures/sprites-small/*.png", {
    eager: true,
    import: "default",
  }),
);

/**
 * Small decorative clutter (books, food, bottles, plants, ...) - always
 * rendered on a layer above furniture in HouseModal, since a book placed
 * "on" a table should show in front of it, not behind.
 */
export const HOUSE_SMALL_ITEMS: HouseSpriteItem[] = [
  {
    id: "bottle-blue-small-1",
    name: "Canned Goods 1",
    price: 10,
    image: images["bottle-blue-small-1.png"] ?? "",
    sizePx: 24,
    slot: { xPct: 31.0, yPct: 19.8 },
  },
  {
    id: "bottle-blue-small-2",
    name: "Canned Goods 2",
    price: 10,
    image: images["bottle-blue-small-2.png"] ?? "",
    sizePx: 24,
    slot: { xPct: 41.0, yPct: 19.8 },
  },
  {
    id: "bottle-blue",
    name: "Empty Glass",
    price: 15,
    image: images["bottle-blue.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 51.0, yPct: 19.8 },
  },
  {
    id: "bottle-red-small",
    name: "Canned Goods 3",
    price: 10,
    image: images["bottle-red-small.png"] ?? "",
    sizePx: 24,
    slot: { xPct: 71.0, yPct: 19.8 },
  },
  {
    id: "bottle-red",
    name: "Choco Drink",
    price: 15,
    image: images["bottle-red.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 81.0, yPct: 19.8 },
  },
  {
    id: "bottle-tan",
    name: "Lemon Drink",
    price: 15,
    image: images["bottle-tan.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 91.0, yPct: 19.8 },
  },
  {
    id: "bottle-white",
    name: "Glass of Milk",
    price: 15,
    image: images["bottle-white.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 11.0, yPct: 29.4 },
  },
  {
    id: "bottle-yellow",
    name: "Orange Juice",
    price: 15,
    image: images["bottle-yellow.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 21.0, yPct: 29.4 },
  },
  {
    id: "bowl-food-oval",
    name: "Bowl Food Oval",
    price: 15,
    image: images["bowl-food-oval.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 31.0, yPct: 29.4 },
  },
  {
    id: "bowl-white",
    name: "Bowl White",
    price: 15,
    image: images["bowl-white.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 41.0, yPct: 29.4 },
  },
  {
    id: "bread-loaf",
    name: "Bread Loaf",
    price: 15,
    image: images["bread-loaf.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 51.0, yPct: 29.4 },
  },
  {
    id: "bread-pie-round",
    name: "Bread Pie Round",
    price: 15,
    image: images["bread-pie-round.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 61.0, yPct: 29.4 },
  },
  {
    id: "bread-small",
    name: "Bread Small",
    price: 10,
    image: images["bread-small.png"] ?? "",
    sizePx: 28,
    slot: { xPct: 71.0, yPct: 29.4 },
  },
  {
    id: "broom",
    name: "Broom",
    price: 15,
    image: images["broom.png"] ?? "",
    sizePx: 31,
    slot: { xPct: 81.0, yPct: 29.4 },
  },
  {
    id: "burger",
    name: "Burger",
    price: 15,
    image: images["burger.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 91.0, yPct: 29.4 },
  },
  {
    id: "coat-hanger",
    name: "Coat Hanger",
    price: 15,
    image: images["coat-hanger.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 11.0, yPct: 39.1 },
  },
  {
    id: "cup-spoon-brown",
    name: "Cup of Coffee",
    price: 15,
    image: images["cup-spoon-brown.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 21.0, yPct: 39.1 },
  },
  {
    id: "cup-spoon-white",
    name: "Empty Cup",
    price: 15,
    image: images["cup-spoon-white.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 31.0, yPct: 39.1 },
  },
  {
    id: "cup-teal",
    name: "Cup of Choco",
    price: 15,
    image: images["cup-teal.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 41.0, yPct: 39.1 },
  },
  {
    id: "dog-bone",
    name: "Dog Bone",
    price: 15,
    image: images["dog-bone.png"] ?? "",
    sizePx: 36,
    slot: { xPct: 61.0, yPct: 39.1 },
  },
  {
    id: "drawer-box-small",
    name: "Brown Box Small",
    price: 20,
    image: images["drawer-box-small.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 71.0, yPct: 39.1 },
  },
  {
    id: "drawer-box",
    name: "Brown Box",
    price: 15,
    image: images["drawer-box.png"] ?? "",
    sizePx: 39,
    slot: { xPct: 81.0, yPct: 39.1 },
  },
  {
    id: "drawer-small-brown",
    name: "Brown Box Big",
    price: 20,
    image: images["drawer-small-brown.png"] ?? "",
    sizePx: 48,
    slot: { xPct: 91.0, yPct: 39.1 },
  },
  {
    id: "drawer-with-items",
    name: "Telephone",
    price: 20,
    image: images["drawer-with-items.png"] ?? "",
    sizePx: 42,
    slot: { xPct: 11.0, yPct: 48.7 },
  },
  {
    id: "dried-fish",
    name: "Towel",
    price: 15,
    image: images["dried-fish.png"] ?? "",
    sizePx: 28,
    slot: { xPct: 21.0, yPct: 48.7 },
  },
  {
    id: "fish-tank",
    name: "Fish Tank",
    price: 20,
    image: images["fish-tank.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 61.0, yPct: 48.7 },
  },
  {
    id: "food-strip-1",
    name: "Pan",
    price: 15,
    image: images["food-strip-1.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 71.0, yPct: 48.7 },
  },
  {
    id: "food-strip-2",
    name: "Pan with Burger",
    price: 15,
    image: images["food-strip-2.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 81.0, yPct: 48.7 },
  },
  {
    id: "food-strip-3",
    name: "Pan with Egg",
    price: 15,
    image: images["food-strip-3.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 91.0, yPct: 48.7 },
  },
  {
    id: "fruit-dark-red",
    name: "Apple",
    price: 15,
    image: images["fruit-dark-red.png"] ?? "",
    sizePx: 28,
    slot: { xPct: 21.0, yPct: 58.3 },
  },
  {
    id: "mug-brown",
    name: "Cup of Tea",
    price: 15,
    image: images["mug-brown.png"] ?? "",
    sizePx: 34,
    slot: { xPct: 41.0, yPct: 58.3 },
  },
  {
    id: "nightstand-small-dark",
    name: "Book",
    price: 10,
    image: images["nightstand-small-dark.png"] ?? "",
    sizePx: 25,
    slot: { xPct: 71.0, yPct: 58.3 },
  },
  {
    id: "open-book",
    name: "Open Book",
    price: 15,
    image: images["open-book.png"] ?? "",
    sizePx: 36,
    slot: { xPct: 81.0, yPct: 58.3 },
  },
  {
    id: "picture-frame-purple",
    name: "Picture Frame Purple",
    price: 20,
    image: images["picture-frame-purple.png"] ?? "",
    sizePx: 39,
    slot: { xPct: 91.0, yPct: 58.3 },
  },
  {
    id: "picture-frame-red",
    name: "Picture Frame Red",
    price: 20,
    image: images["picture-frame-red.png"] ?? "",
    sizePx: 50,
    slot: { xPct: 11.0, yPct: 67.9 },
  },
  {
    id: "plate-food-1",
    name: "Plate Food 1",
    price: 15,
    image: images["plate-food-1.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 21.0, yPct: 67.9 },
  },
  {
    id: "plate-food-2",
    name: "Plate Food 2",
    price: 15,
    image: images["plate-food-2.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 31.0, yPct: 67.9 },
  },
  {
    id: "plate-food-3",
    name: "Plate Food 3",
    price: 15,
    image: images["plate-food-3.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 41.0, yPct: 67.9 },
  },
  {
    id: "plate-white-oval",
    name: "Plate White Oval",
    price: 15,
    image: images["plate-white-oval.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 51.0, yPct: 67.9 },
  },
  {
    id: "pot-brown",
    name: "Hot Pot 1",
    price: 20,
    image: images["pot-brown.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 61.0, yPct: 67.9 },
  },
  {
    id: "pot-maroon",
    name: "Hot Pot 2",
    price: 20,
    image: images["pot-maroon.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 71.0, yPct: 67.9 },
  },
  {
    id: "pot-red-1",
    name: "Hot Pot 3",
    price: 20,
    image: images["pot-red-1.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 81.0, yPct: 67.9 },
  },
  {
    id: "pot-red-2",
    name: "Hot Pot 4",
    price: 20,
    image: images["pot-red-2.png"] ?? "",
    sizePx: 45,
    slot: { xPct: 91.0, yPct: 67.9 },
  },
  {
    id: "potted-cactus",
    name: "Potted Cactus",
    price: 15,
    image: images["potted-cactus.png"] ?? "",
    sizePx: 28,
    slot: { xPct: 11.0, yPct: 77.6 },
  },
  {
    id: "potted-plant-small",
    name: "Potted Plant Small",
    price: 20,
    image: images["potted-plant-small.png"] ?? "",
    sizePx: 36,
    slot: { xPct: 21.0, yPct: 77.6 },
  },
  {
    id: "rolling-pin",
    name: "Hanged Clothes",
    price: 15,
    image: images["rolling-pin.png"] ?? "",
    sizePx: 24,
    slot: { xPct: 31.0, yPct: 77.6 },
  },
  {
    id: "rubber-duck",
    name: "Rubber Duck",
    price: 15,
    image: images["rubber-duck.png"] ?? "",
    sizePx: 36,
    slot: { xPct: 41.0, yPct: 77.6 },
  },
  {
    id: "spice-bottle",
    name: "Candle",
    price: 10,
    image: images["spice-bottle.png"] ?? "",
    sizePx: 24,
    slot: { xPct: 51.0, yPct: 77.6 },
  },
  {
    id: "teapot",
    name: "Teapot",
    price: 20,
    image: images["teapot.png"] ?? "",
    sizePx: 48,
    slot: { xPct: 61.0, yPct: 77.6 },
  },
  {
    id: "tissue-cloud",
    name: "Paper",
    price: 10,
    image: images["tissue-cloud.png"] ?? "",
    sizePx: 28,
    slot: { xPct: 81.0, yPct: 77.6 },
  },
  {
    id: "wall-clock",
    name: "Wall Clock",
    price: 20,
    image: images["wall-clock.png"] ?? "",
    sizePx: 48,
    slot: { xPct: 91.0, yPct: 77.6 },
  },
];

export function findHouseSmallItem(id: string): HouseSpriteItem | undefined {
  return HOUSE_SMALL_ITEMS.find((i) => i.id === id);
}
